import type { CommandId } from "@firefox-cli/protocol";
import { actionParamsFor } from "./browser-commands-test-utils.js";

export const browserSmokeRequests = new Map<CommandId, unknown>([
  ["tabs.list", {}],
  ["tab.new", {}],
  ["tab.select", { target: { tab: { kind: "active" } } }],
  ["tab.close", { target: { tab: { kind: "active" } } }],
  ["windows.list", {}],
  ["window.new", {}],
  ["window.select", { target: { window: { kind: "active" } } }],
  ["window.close", { target: { window: { kind: "active" } } }],
  ["open", { url: "https://example.test/done", newTab: false }],
  ["back", {}],
  ["forward", {}],
  ["reload", {}],
  ["snapshot", {}],
  ["ref.resolve", { ref: "@e1", generationId: "g1" }],
  ["get", { kind: "title" }],
  ["is", { kind: "visible", selector: "button" }],
  ["wait", { kind: "url", urlGlob: "https://example.test/*" }],
  ["eval", { script: "document.title", source: "argv" }],
  ["screenshot", { path: "/tmp/page.png", format: "png" }],
  ["drag", actionParamsFor("drag")],
  ["upload", actionParamsFor("upload")],
  ["mouse", actionParamsFor("mouse")],
  ["keydown", actionParamsFor("keydown")],
  ["keyup", actionParamsFor("keyup")],
  ["find", { kind: "text", value: "Submit" }],
  ["frame", {}],
  ["download", { url: "https://example.test/file.txt" }],
  ["dialog", { action: "status" }],
  ["clipboard", { action: "read" }],
  ["cookies", { action: "list", url: "https://example.test/" }],
  ["storage", { area: "local", action: "get" }],
  ["network", { action: "list" }],
  ["console", { action: "list" }],
  ["errors", { action: "list" }],
  ["highlight", { selector: "button" }],
  ["notify", { title: "Action needed" }],
  ["pdf", { path: "/tmp/page.pdf" }],
  ["set.viewport", { width: 1200, height: 800 }],
  ["diff", { kind: "title", expected: "Expected title" }],
  ["batch", { steps: [{ command: "snapshot", params: {} }] }],
  ["click", actionParamsFor("click")],
  ["dblclick", actionParamsFor("dblclick")],
  ["focus", actionParamsFor("focus")],
  ["hover", actionParamsFor("hover")],
  ["fill", actionParamsFor("fill")],
  ["type", actionParamsFor("type")],
  ["press", actionParamsFor("press")],
  ["keyboard.type", actionParamsFor("keyboard.type")],
  ["keyboard.inserttext", actionParamsFor("keyboard.inserttext")],
  ["check", actionParamsFor("check")],
  ["uncheck", actionParamsFor("uncheck")],
  ["select", actionParamsFor("select")],
  ["scroll", actionParamsFor("scroll")],
  ["scrollintoview", actionParamsFor("scrollintoview")],
  ["swipe", actionParamsFor("swipe")],
  ["pair.openApproval", {}],
]);
