import {
  elementActionParamsSchema,
  elementActionResultSchemaFor,
  keyboardTextActionParamsSchema,
  pressParamsSchema,
  scrollActionResultSchemaFor,
  scrollParamsSchema,
  selectActionResultSchema,
  selectParamsSchema,
  textActionParamsSchema,
  textActionResultSchemaFor,
} from "../actions.js";
import { defineCommandEntries } from "./define.js";

export const actionsCommandEntries = defineCommandEntries({
  click: {
    params: elementActionParamsSchema,
    result: elementActionResultSchemaFor("click"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "click", path: ["click"], batch: true, selectorDimensions: "both" }],
  },
  dblclick: {
    params: elementActionParamsSchema,
    result: elementActionResultSchemaFor("dblclick"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "dblclick", path: ["dblclick"], batch: true, selectorDimensions: "both" }],
  },
  focus: {
    params: elementActionParamsSchema,
    result: elementActionResultSchemaFor("focus"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "focus", path: ["focus"], batch: true, selectorDimensions: "both" }],
  },
  hover: {
    params: elementActionParamsSchema,
    result: elementActionResultSchemaFor("hover"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "hover", path: ["hover"], batch: true, selectorDimensions: "both" }],
  },
  fill: {
    params: textActionParamsSchema,
    result: textActionResultSchemaFor("fill"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "fill", path: ["fill"], batch: true, selectorDimensions: "both" }],
  },
  type: {
    params: textActionParamsSchema,
    result: textActionResultSchemaFor("type"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "type", path: ["type"], batch: true, selectorDimensions: "both" }],
  },
  press: {
    params: pressParamsSchema,
    result: elementActionResultSchemaFor("press"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "press", path: ["press"], batch: true, selectorDimensions: "both" }],
  },
  "keyboard.type": {
    params: keyboardTextActionParamsSchema,
    result: textActionResultSchemaFor("keyboard.type"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "keyboard.type", path: ["keyboard", "type"], batch: true, selectorDimensions: "both" }],
  },
  "keyboard.inserttext": {
    params: keyboardTextActionParamsSchema,
    result: textActionResultSchemaFor("keyboard.inserttext"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "keyboard.inserttext", path: ["keyboard", "inserttext"], batch: true, selectorDimensions: "both" }],
  },
  check: {
    params: elementActionParamsSchema,
    result: elementActionResultSchemaFor("check"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "check", path: ["check"], batch: true, selectorDimensions: "both" }],
  },
  uncheck: {
    params: elementActionParamsSchema,
    result: elementActionResultSchemaFor("uncheck"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "uncheck", path: ["uncheck"], batch: true, selectorDimensions: "both" }],
  },
  select: {
    params: selectParamsSchema,
    result: selectActionResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "select", path: ["select"], batch: true, selectorDimensions: "both" }],
  },
  scroll: {
    params: scrollParamsSchema,
    result: scrollActionResultSchemaFor("scroll"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "scroll", path: ["scroll"], batch: true, selectorDimensions: "both" }],
  },
  scrollintoview: {
    params: elementActionParamsSchema,
    result: elementActionResultSchemaFor("scrollintoview"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "scrollintoview", path: ["scrollintoview"], batch: true, selectorDimensions: "both" }],
  },
  swipe: {
    params: scrollParamsSchema,
    result: scrollActionResultSchemaFor("swipe"),
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "swipe", path: ["swipe"], batch: true, selectorDimensions: "both" }],
  },
});
