import {
  navigationParamsSchema,
  navigationResultSchema,
  openParamsSchema,
  tabCloseResultSchema,
  tabNewParamsSchema,
  tabNewResultSchema,
  tabsListParamsSchema,
  tabsListResultSchema,
  tabTargetParamsSchema,
  windowCloseResultSchema,
  windowNewParamsSchema,
  windowNewResultSchema,
  windowSelectResultSchema,
  windowsListParamsSchema,
  windowsListResultSchema,
  windowTargetParamsSchema,
} from "../target.js";
import { defineCommandEntries } from "./define.js";

export const browsingCommandEntries = defineCommandEntries({
  "tabs.list": {
    params: tabsListParamsSchema,
    result: tabsListResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "tab.list", path: ["tab"], batch: true, selectorDimensions: "window" }],
  },
  "tab.new": {
    params: tabNewParamsSchema,
    result: tabNewResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "tab.new", path: ["tab", "new"], batch: true, selectorDimensions: "window" }],
  },
  "tab.select": {
    params: tabTargetParamsSchema,
    result: tabNewResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "tab.select", path: ["tab", "select"], batch: true, selectorDimensions: "both" }],
  },
  "tab.close": {
    params: tabTargetParamsSchema,
    result: tabCloseResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "tab.close", path: ["tab", "close"], batch: true, selectorDimensions: "both" }],
  },
  "windows.list": {
    params: windowsListParamsSchema,
    result: windowsListResultSchema,
    status: "mvp",
    owner: "extension",
    target: "none",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true },
    cliRoutes: [{ id: "window.list", path: ["window"], batch: true, selectorDimensions: "neither" }],
  },
  "window.new": {
    params: windowNewParamsSchema,
    result: windowNewResultSchema,
    status: "mvp",
    owner: "extension",
    target: "none",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true },
    cliRoutes: [{ id: "window.new", path: ["window", "new"], batch: true, selectorDimensions: "neither" }],
  },
  "window.select": {
    params: windowTargetParamsSchema,
    result: windowSelectResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "window.select", path: ["window", "select"], batch: true, selectorDimensions: "window" }],
  },
  "window.close": {
    params: windowTargetParamsSchema,
    result: windowCloseResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "window.close", path: ["window", "close"], batch: true, selectorDimensions: "window" }],
  },
  open: {
    params: openParamsSchema,
    result: navigationResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "open", path: ["open"], batch: true, selectorDimensions: "both" }],
  },
  back: {
    params: navigationParamsSchema,
    result: navigationResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "back", path: ["back"], batch: true, selectorDimensions: "both" }],
  },
  forward: {
    params: navigationParamsSchema,
    result: navigationResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "forward", path: ["forward"], batch: true, selectorDimensions: "both" }],
  },
  reload: {
    params: navigationParamsSchema,
    result: navigationResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "reload", path: ["reload"], batch: true, selectorDimensions: "both" }],
  },
});
