import {
  getParamsSchema,
  getResultSchema,
  isParamsSchema,
  isResultSchema,
  refResolveParamsSchema,
  refResolveResultSchema,
  snapshotParamsSchema,
  snapshotResultSchema,
  waitParamsSchema,
  waitResultSchema,
} from "../content.js";
import { defineCommandEntries } from "./define.js";

export const contentCommandEntries = defineCommandEntries({
  snapshot: {
    params: snapshotParamsSchema,
    result: snapshotResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    frameScope: {
      scope: "main-frame-with-iframe-diagnostics",
      reason: "Snapshot refs are generated for the main frame; iframe entries are diagnostic/read-only.",
      future: "docs/iframe-targeting-future.md",
    },
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "snapshot", path: ["snapshot"], batch: true, selectorDimensions: "both" }],
  },
  "ref.resolve": {
    params: refResolveParamsSchema,
    result: refResolveResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "ref", path: ["ref"], batch: true, selectorDimensions: "both" }],
  },
  get: {
    params: getParamsSchema,
    result: getResultSchema,
    status: "mvp",
    owner: "extension",
    target: "mixed",
    content: "mixed",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "get", path: ["get"], batch: true, selectorDimensions: "both" }],
  },
  is: {
    params: isParamsSchema,
    result: isResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "is", path: ["is"], batch: true, selectorDimensions: "both" }],
  },
  wait: {
    params: waitParamsSchema,
    result: waitResultSchema,
    status: "mvp",
    owner: "extension",
    target: "mixed",
    content: "mixed",
    action: false,
    timeout: "command",
    security: {
      level: "conditional",
      reasons: ["page-function-evaluation", "downloads", "network-observation"],
    },
    compatibility: {
      requirements: [
        {
          minProtocolVersion: 2,
          reason: "Network-idle waits are scoped to the resolved tab.",
          params: {
            matches: [
              { path: ["kind"], equals: "load-state" },
              { path: ["state"], equals: "networkidle" },
            ],
          },
        },
      ],
    },
    batch: { allowed: true, extensionDefaultTarget: true, timeoutRebase: true },
    cliRoutes: [{ id: "wait", path: ["wait"], batch: true, selectorDimensions: "both" }],
  },
});
