import {
  pairApproveParamsSchema,
  pairApproveResultSchema,
  pairOpenApprovalParamsSchema,
  pairOpenApprovalResultSchema,
  pairRequestApprovalParamsSchema,
  pairRequestApprovalResultSchema,
  pairResetParamsSchema,
  pairResetResultSchema,
} from "../pairing.js";
import { defineCommandEntries } from "./define.js";

export const pairingCommandEntries = defineCommandEntries({
  "pair.approve": {
    params: pairApproveParamsSchema,
    result: pairApproveResultSchema,
    status: "mvp",
    owner: "native-host",
    target: "none",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: false },
    cliRoutes: [],
  },
  "pair.reset": {
    params: pairResetParamsSchema,
    result: pairResetResultSchema,
    status: "mvp",
    owner: "native-host",
    target: "none",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: false },
    cliRoutes: [],
  },
  "pair.requestApproval": {
    params: pairRequestApprovalParamsSchema,
    result: pairRequestApprovalResultSchema,
    status: "mvp",
    owner: "extension",
    target: "none",
    content: "never",
    action: false,
    timeout: "none",
    compatibility: {
      requirements: [
        {
          minProtocolVersion: 4,
          reason: "CLI approval requests use a dedicated decision page and wait for explicit user approval or denial.",
        },
      ],
    },
    batch: { allowed: false },
    cliRoutes: [{ id: "connect", path: ["connect"], batch: false }],
  },
  "pair.openApproval": {
    params: pairOpenApprovalParamsSchema,
    result: pairOpenApprovalResultSchema,
    status: "mvp",
    owner: "extension",
    target: "none",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: false },
    cliRoutes: [],
  },
});
