import { actionResultSchema } from "../actions.js";
import {
  clipboardParamsSchema,
  clipboardResultSchema,
  consoleParamsSchema,
  consoleResultSchema,
  cookieParamsSchema,
  cookieResultSchema,
  dialogParamsSchema,
  dialogResultSchema,
  diffParamsSchema,
  diffResultSchema,
  downloadParamsSchema,
  downloadResultSchema,
  dragParamsSchema,
  errorsParamsSchema,
  errorsResultSchema,
  evalParamsSchema,
  evalResultSchema,
  findParamsSchema,
  findResultSchema,
  frameParamsSchema,
  frameResultSchema,
  highlightParamsSchema,
  highlightResultSchema,
  keyEventParamsSchema,
  mouseParamsSchema,
  networkParamsSchema,
  networkResultSchema,
  notifyParamsSchema,
  notifyResultSchema,
  pdfParamsSchema,
  pdfResultSchema,
  screenshotParamsSchema,
  screenshotResultSchema,
  setViewportParamsSchema,
  setViewportResultSchema,
  storageParamsSchema,
  storageResultSchema,
  uploadParamsSchema,
} from "../browser.js";
import { defineCommandEntries } from "./define.js";

export const phase8CommandEntries = defineCommandEntries({
  eval: {
    params: evalParamsSchema,
    result: evalResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "command",
    security: { level: "sensitive", reasons: ["page-code-execution"] },
    frameScope: {
      scope: "main-frame-only",
      reason: "Eval runs in the resolved tab's main frame; iframe targeting is not implemented.",
      future: "docs/iframe-targeting-future.md",
    },
    batch: { allowed: true, extensionDefaultTarget: true, timeoutRebase: true },
    cliRoutes: [{ id: "eval", path: ["eval"], batch: true }],
  },
  screenshot: {
    params: screenshotParamsSchema,
    result: screenshotResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "command",
    batch: { allowed: true, extensionDefaultTarget: true, timeoutRebase: true },
    cliRoutes: [{ id: "screenshot", path: ["screenshot"], batch: true }],
  },
  drag: {
    params: dragParamsSchema,
    result: actionResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "drag", path: ["drag"], batch: true }],
  },
  upload: {
    params: uploadParamsSchema,
    result: actionResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "upload", path: ["upload"], batch: true }],
  },
  mouse: {
    params: mouseParamsSchema,
    result: actionResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "mouse", path: ["mouse"], batch: true }],
  },
  keydown: {
    params: keyEventParamsSchema,
    result: actionResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "keydown", path: ["keydown"], batch: true }],
  },
  keyup: {
    params: keyEventParamsSchema,
    result: actionResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "action",
    action: true,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "keyup", path: ["keyup"], batch: true }],
  },
  find: {
    params: findParamsSchema,
    result: findResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "find", path: ["find"], batch: true }],
  },
  frame: {
    params: frameParamsSchema,
    result: frameResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    frameScope: {
      scope: "main-frame-with-iframe-diagnostics",
      reason: "The frame command lists iframe diagnostics from the main frame only.",
      future: "docs/iframe-targeting-future.md",
    },
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "frame", path: ["frame"], batch: true }],
  },
  download: {
    params: downloadParamsSchema,
    result: downloadResultSchema,
    status: "mvp",
    owner: "extension",
    target: "none",
    content: "never",
    action: false,
    timeout: "none",
    security: { level: "sensitive", reasons: ["downloads"] },
    batch: { allowed: true },
    cliRoutes: [{ id: "download", path: ["download"], batch: true }],
  },
  dialog: {
    params: dialogParamsSchema,
    result: dialogResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "dialog", path: ["dialog"], batch: true }],
  },
  clipboard: {
    params: clipboardParamsSchema,
    result: clipboardResultSchema,
    status: "mvp",
    owner: "extension",
    target: "mixed",
    content: "mixed",
    action: false,
    timeout: "none",
    security: { level: "sensitive", reasons: ["clipboard"] },
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "clipboard", path: ["clipboard"], batch: true }],
  },
  cookies: {
    params: cookieParamsSchema,
    result: cookieResultSchema,
    status: "mvp",
    owner: "extension",
    target: "none",
    content: "never",
    action: false,
    timeout: "none",
    security: { level: "sensitive", reasons: ["cookies"] },
    batch: { allowed: true },
    cliRoutes: [{ id: "cookies", path: ["cookies"], batch: true }],
  },
  storage: {
    params: storageParamsSchema,
    result: storageResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "storage", path: ["storage"], batch: true }],
  },
  network: {
    params: networkParamsSchema,
    result: networkResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    security: { level: "sensitive", reasons: ["network-observation"] },
    compatibility: {
      requirements: [
        {
          minProtocolVersion: 2,
          reason: "Network commands are scoped to the resolved tab.",
        },
      ],
    },
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "network", path: ["network"], batch: true }],
  },
  console: {
    params: consoleParamsSchema,
    result: consoleResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "console", path: ["console"], batch: true }],
  },
  errors: {
    params: errorsParamsSchema,
    result: errorsResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "errors", path: ["errors"], batch: true }],
  },
  highlight: {
    params: highlightParamsSchema,
    result: highlightResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "always",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "highlight", path: ["highlight"], batch: true }],
  },
  notify: {
    params: notifyParamsSchema,
    result: notifyResultSchema,
    status: "mvp",
    owner: "extension",
    target: "none",
    content: "never",
    action: false,
    timeout: "none",
    security: { level: "sensitive", reasons: ["notifications"] },
    compatibility: {
      requirements: [
        {
          minProtocolVersion: 4,
          reason: "Native notifications were added in protocol v4.",
        },
      ],
    },
    batch: { allowed: true },
    cliRoutes: [{ id: "notify", path: ["notify"], batch: true }],
  },
  pdf: {
    params: pdfParamsSchema,
    result: pdfResultSchema,
    status: "unsupported",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true },
    cliRoutes: [{ id: "pdf", path: ["pdf"], batch: true }],
  },
  "set.viewport": {
    params: setViewportParamsSchema,
    result: setViewportResultSchema,
    status: "mvp",
    owner: "extension",
    target: "optional",
    content: "never",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "set.viewport", path: ["set", "viewport"], batch: true }],
  },
  diff: {
    params: diffParamsSchema,
    result: diffResultSchema,
    status: "mvp",
    owner: "extension",
    target: "mixed",
    content: "mixed",
    action: false,
    timeout: "none",
    batch: { allowed: true, extensionDefaultTarget: true },
    cliRoutes: [{ id: "diff", path: ["diff"], batch: true }],
  },
});
